### PR TITLE
GUACAMOLE-86: Remove terminal emulator's STDOUT pipe.

### PR DESCRIPTION
**Pull request by mike-jumper**
This change removes use of the STDOUT pipe entirely, replacing the blocking/signaling functionality with a `pthread_cond_t` and corresponding mutex. Writes which previously would go through the pipe now go through direct calls to `guac_terminal_write()`.

### CODE REVIEW

**Comment by jmuehlner** [comment]
@flangelo Any thoughts on this change? You're probably more familiar with a lot of this code.

**Comment by flangelo** [comment]
It looks good. Great work @mike-jumper .

**Comment by jmuehlner** [comment]
@flangelo Go for it - merge away! :shipit:

**Comment by mike-jumper** [comment]
Also beware: since the 0.9.11-incubating release branch exists, and this is a 0.9.11-incubating change, it needs to be merged to `staging/0.9.11-incubating` first, followed by `staging/0.9.11-incubating` to `master`.

**Pull request merged**
