### PR TITLE
GUACAMOLE-208: Define new status codes for network/connection state. Leverage within protocol support.

### PR DESCRIPTION
**Pull request by mike-jumper**

### CODE REVIEW

**Comment by jmuehlner** [comment]
Why only leverage these within RDP? These look pretty universal.

**Comment by mike-jumper** [comment]
Fair enough. I'll quickly update the status code usage elsewhere.

**Comment by mike-jumper** [comment]
The branch name is somewhat silly now, but the other protocols should be OK. It turns out they were already pretty alright with the existing codes - only `UPSTREAM_NOT_FOUND` was relevant (for network connect failures).

**Comment by jmuehlner** [comment]
All right, looks good to me now!

**Comment by flangelo** [comment]
+1

**Pull request merged**
