### PR TITLE
GUACAMOLE-314: Bump version to 0.9.13-incubating.

### PR DESCRIPTION
**Pull request by mike-jumper**

### CODE REVIEW

**Comment by mike-jumper** [comment]
**NOTE:** Intended for `staging/0.9.13-incubating`.

**Comment by necouchman** [comment]
Looks good to me.

**Comment by mike-jumper** [comment]
> Looks good to me.

Sooooooo ... want to give the slightly-more-difficult-to-remember release-specific merge a shot?

http://guacamole.incubator.apache.org/pull-requests/#merging-release-specific-changes

It *should* be as simple as the merges you've already done, except:

1. Release-specific changes get merged to the staging branch first, in this case `staging/0.9.13-incubating`.
2. Once merged to the staging branch, it is the staging branch which gets merged to `master`.

**Comment by necouchman** [comment]
Okay...did it on the server repo to the staging branch...want to check my work and make sure that's good before I do the others, and before it gets merged to master?

**Comment by necouchman** [comment]
Went ahead and merged the rest of them to the staging branches...to get it from staging to master, is it just:
git checkout upstream/master
git pull upstream/staging/0.9.13-incubating
git push upstream master

??

**Comment by mike-jumper** [comment]
Pretty much. Merging staging to master is essentially the same as merging any other branch to master (like one containing the changes of a pull request):

1. Ensure you are up-to-date with upstream:

       git fetch upstream

2. Switch to your copy of master:

       git checkout master

3. Update your copy of master to match upstream:

       git merge --ff-only upstream/master

4. Merge the staging branch, noting that you're merging 0.9.13-incubating change back to master in the commit message (see http://guacamole.incubator.apache.org/pull-requests/#merging-release-specific-changes):

       git merge --no-ff staging/0.9.13-incubating

5. Check that the commits look sane with `git log upstream/master..HEAD` and, when ready, throw the third switch:

       git push upstream master

As long as you don't see anything unexpected in the logs (there should just be the commits from the merged PR, the merge commit from that PR, and the merge commit for staging to master), you should be good to go.

**Comment by necouchman** [comment]
Got it, all done.

**Pull request merged**
