### PR TITLE
GUACAMOLE-135: Add Swiss/French keymap for RDP

### PR DESCRIPTION
**Pull request by Robin-73**
add fr_ch keyboard layout support

### CODE REVIEW

**Comment by jmuehlner** [comment]
Hello Robin-73; thanks for the contribution!

Please note that all contributions require an associated JIRA ticket - see https://github.com/apache/incubator-guacamole-client/blob/master/CONTRIBUTING for more details.

**Comment by mike-jumper** [comment]
Though not obvious from the PR itself, there is indeed JIRA issue:

https://issues.apache.org/jira/browse/GUACAMOLE-135

The commit message does need to be amended to tag the JIRA issue like all
other messages in the history, however.

**Comment by mike-jumper** [comment]
@Robin-73, in addition to updating the commit message to tag the JIRA issue, you will also need to add your keymap to `src/protocols/rdp/Makefile.am`, so it gets built automatically along with the others:

https://github.com/Robin-73/incubator-guacamole-server/blob/a28b55ea5bd1b51e3f08cd90b84517710a2d7b4a/src/protocols/rdp/Makefile.am#L244-L252

**Comment by Robin-73** [comment]
quiet new on github, so hope i have done things correctly...

**Comment by mike-jumper** [comment]
> quiet new on github, so hope i have done things correctly...

No problem. You're getting close, but:

* There are quite a few commits now, all of which cover the same change - they should be combined.
* Your other recent commit, "Update Makefile.am", lacks the JIRA issue.
* Looking through the latest version of your keymap, I see that you are using tabs to align things. Please only use spaces for consistency's sake. No other part of our codebase uses tabs.

Ideally, you would probably want only "GUACAMOLE-135: Add Swiss/French keymap for RDP", since that is the high-level change happening here. The statements "add fr_ch_qwertz.keymap" and "update Makefile.am" are suboptimal because they add no information beyond what git already tells us.

Are you familiar with git's interactive rebase? That would probably be the best way to squash these commits together and reword:

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by jmroth** [comment]
@Robin-73  Could you remove the branch that you created this pull request from (or just delete the pull request if possible) since the issue has actually been resolved ;-)

**Comment by necouchman** [comment]
@Robin-73: Please close this PR.

**Pull request closed without merging**
